- hosts: application_nodes
  become: yes
  vars:
    jar_source: "./target/hello-world-0.0.1-SNAPSHOT.jar"
    jar_destination: "/opt/application/hello-world.jar"
    app_user: "hello_world_user"
  tasks:
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/hello-rest-service/hello-rest-service.yml


- hosts: proxy-server
  become: yes
  gather_facts: yes
  vars:
    domain_name: "tomaszjarosz.pl"
    service_admin_email: "tomaszjarosz1994@gmail.com"
    service_name: "tomaszjarosz.pl"
    service_host: "tomaszjarosz.pl"
    service_root_directory: "/opt"
    letsencrypt_ssl_dir: "/etc/letsencrypt/live"
  tasks:
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/nginx/nginx.yml