- hosts: application_nodes
  become: yes
  vars:
    jar_source: "./target/hello-world-0.0.1-SNAPSHOT.jar"
    jar_destination: "/opt/application/hello-world.jar"
    app_user: "hello_world_user"
  tasks:
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/hello-rest-service/hello-rest-service.yml
    
    
- hosts: stats_nodes
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
    db_node_ip: 127.0.0.1
    metric_store_ip: 127.0.0.1
  tasks:
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/grafana-influx/tasks/os-dependencies.yml
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/grafana-influx/tasks/telegraf.yml
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/grafana-influx/tasks/influx.yml
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/grafana-influx/tasks/grafana.yml
  


- hosts: proxy-server
  become: yes
  gather_facts: yes
  vars:
    domain_name: "tomekj.pl"
    service_admin_email: "tomaszjarosz1994@gmail.com"
    service_root_directory: "/opt"
    letsencrypt_ssl_dir: "/etc/letsencrypt/live"
  tasks:
    - include_tasks: /home/ec2-user/environment/adsk/projekt_zaliczeniowy/aws-secured-environment/nginx/nginx.yml