---
- name: "Copy http config for wordpress"
  template:
    src: templates/public/wp_http.config
    dest: /etc/httpd/conf.d/blog.conf
    
- name: "Start web server"
  service:
    name: httpd
    state: restarted