- hosts: proxy
  become: yes
  vars:
    domain_name: "tomaszjarosz.pl"
    letsencrypt_email: "tomaszjarosz1994@gmail.com"
  tasks:
  
    - name: "Install git"
      yum:
        name: git
        state: latest
        
    - name: "enable epel repository"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        
    - name: "enable epel repository"
      shell: yum-config-manager --enable epel
      
    - name: "enable epel repository"
      shell: yum repolist
      
    - name: "install nginx"
      yum:
        name: nginx
        
    - name: "start nginx service"
      service:
        name: nginx
        state: started
        
    - name: "copy nginx conf"
      template:
        src: template/nginx.conf
        dest: "/etc/nginx/nginx.conf"
        
    - name: "reload nginx service"
      service:
        name: nginx
        state: reloaded
        
    - name: "install python"
      yum:
        name: python2-certbot-nginx
        
    - name: "get certbot"
      git: 
        repo: https://github.com/letsencrypt/letsencrypt 
        version: master
        dest: /opt/letsencrypt
        clone: yes
        
    - shell: sudo certbot -i nginx -d "tomaszjarosz.pl" --nginx -m "tomaszjarosz1994@gmail.com" --agree-tos --redirect 
    - service:
        name: nginx
        state: restarted    
    - name: "run letsencrypt debug"
      shell: /opt/letsencrypt/letsencrypt-auto --debug
    - name: config file
      shell: echo "rsa-key-size = 4096" >> /etc/letsencrypt/config.ini
      shell: echo "email = tomasz.jarosz1994@gmail.com" >> /etc/letsencrypt/config.ini
 
 
