---
- name: "Yum install grafana"
  yum:
    name: "{{grafana_url}}"
    state: present
- name: "Put cfg in place"
  template:
    src: templates/grafana.ini
    dest: /etc/grafana/grafana.ini

- name: "add any source, in our case influx db"
  service:
    name: "grafana-server"
    state: restarted

- name: "Create influxdb datasource"
  grafana_datasource:
    name: "my_influx"
    grafana_url: "http://127.0.0.1:8080"
    grafana_user: "admin"
    grafana_password: "admin"
    ds_type: "influxdb"
    url: "http://localhost:8086"
    database: "metrics"
    access: direct
    is_default: yes
- copy:
    src: templates/dashboard/my.json
    dest: /tmp/my.json
- copy:
    src: templates/dashboard/apache.json
    dest: /tmp/apache.json
- name: "create my dashboard"
  grafana_dashboard:
    grafana_url: "http://127.0.0.1:8080"
    state: present
    message: "Updated by ansible"
    overwrite: yes
    slug: "apache"
    path: /tmp/apache.json