---
- name: "install grafana"
  yum:
    name: "{{grafana_url}}"
    state: present
- name: "Put cfg in place"
  template:
    src: ../templates/grafana.ini
    dest: /etc/grafana/grafana.ini

- name: "start grafana server"
  service:
    name: "grafana-server"
    state: restarted

- name: "Create influxdb datasource"
  grafana_datasource:
    name: "my_influx"
    grafana_url: "http://127.0.0.1:8080"
    grafana_user: "admin"
    grafana_password: "admin"
    ds_type: "influxdb"
    url: "http://localhost:8086"
    database: "metrics"
    access: direct
    is_default: yes