---
- hosts: web_nodes
  become: yes
  vars:
    wordpress_path: /var/www/wordpress
    db_node_ip: 18.195.217.30
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metric_store_ip: 18.195.217.30
  tasks:
    - include_tasks: tasks/public/os-dependencies.yml
    - include_tasks: tasks/public/install-wordpress.yml
    - include_tasks: tasks/public/configure-apache.yml
    - include_tasks: tasks/public/install-telegraf.yml

- hosts: db_nodes
  become: yes
  vars:
    web_nodes: 18.195.217.30
  tasks:
    - include_tasks: tasks/private/os-dependencies.yml
    - include_tasks: tasks/private/create-wordpress-database.yml






















- hosts: stats_nodes
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
    metric_store_ip: 127.0.0.1
  tasks:
    - include_tasks: tasks/influx.yml
    - include_tasks: tasks/grafana.yml
  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    