
- hosts: stats_nodes
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
    db_node_ip: 127.0.0.1
    metric_store_ip: 127.0.0.1
  tasks:
    - include_tasks: tasks/os-dependencies.yml
    - include_tasks: tasks/telegraf.yml
    - include_tasks: tasks/influx.yml
    - include_tasks: tasks/grafana.yml
  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    