---
- hosts: application_nodes
  become: yes
  vars:
     jar_source: /jar/location/todo
     jar_destination: /opt/app_root/app.jar
     app_user: application_user
  tasks:
    - name: "install jre"
      yum: 
         name: java-1.8.0-openjdk
         state: present
         
    - name: "create path"
      file:
         path: /opt/application
         state: directory
         
    - name: "copy.jar to remote machine"
      copy:
        src: "{{jar_location}}"
        dest: "{{app_location}}"
        
    - name: "create user"    
      user:
         name: "{{app_user}}
      
     - template: 
         src:  template/carrental.service
         dest: /etc/systemd/system/carrental.service
        
    - name: 
      systemd:
        name: carrental
        daemon_reload: yes
        state: restarted